/*

 BACKGROUNDS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Development\gameboy-demo\res\backgrounds.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Backgrounds_h_INCLUDE
#define __Backgrounds_h_INCLUDE

#define BackgroundsWidth 20
#define BackgroundsHeight 18
#define BackgroundsBank 0

extern const unsigned char Backgrounds[];

#endif

/* End of BACKGROUNDS.H */
